name: GitHub Readme Update
on:
  schedule:
    # At 12:00 AM, on day 1 of the month
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          base_url: https://ytcards.vercel.app/
          channel_id: UCLGu2XnVNG48HQtqTXQRptA

      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
